# Generated by Django 5.2 on 2025-04-27 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("country", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Exporter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(default="Not Provided", max_length=200)),
                ("phone", models.CharField(default="Not Provided", max_length=50)),
                (
                    "contact_person",
                    models.CharField(default="Not Provided", max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("port_code", models.CharField(max_length=50)),
                ("shipping_bill_no", models.CharField(max_length=100)),
                ("shipping_bill_date", models.DateField()),
                ("iec", models.CharField(max_length=100)),
                ("exporter_address", models.CharField(max_length=300)),
                ("exporter_city_state", models.CharField(max_length=200)),
                ("exporter_pin", models.CharField(max_length=20)),
                ("destination_port", models.CharField(max_length=100)),
                ("destination_country", models.CharField(max_length=100)),
                ("invoice_no", models.CharField(max_length=100)),
                ("ritc", models.CharField(max_length=20)),
                ("item", models.CharField(max_length=300)),
                ("quantity", models.FloatField()),
                ("uqc", models.CharField(max_length=10)),
                ("item_rate", models.FloatField()),
                ("currency", models.CharField(max_length=10)),
                ("fob", models.FloatField()),
                ("cha_name", models.CharField(max_length=200)),
                ("leo_date", models.DateField()),
                ("invoice_sr_no", models.IntegerField()),
                ("item_no", models.IntegerField()),
                ("drawback", models.FloatField(blank=True, null=True)),
                (
                    "consignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="export_dashboard.consignee",
                    ),
                ),
                (
                    "exporter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="export_dashboard.exporter",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="export_dashboard.product",
                    ),
                ),
            ],
        ),
    ]
