# Generated by Django 5.2 on 2025-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrecord",
            name="leo_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
