# Generated by Django 5.2 on 2025-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export_dashboard", "0002_alter_exportrecord_leo_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportrecord",
            name="invoice_sr_no",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exportrecord",
            name="item_no",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
